on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: A job to automate contribute list in readme.md
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@v2.3.6
              with:
                  readme_path: "contributors.md"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
